### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Timmmm** [srl295/srl-unicode-proposals#13]
(Sorry if this is the wrong place for this)

I'm glad someone is working on this, but have you considered the copyright issues? I can predict what will happen:

Apple and WhatsApp will adopt this new system and add a load of new copyrighted emojis. These will become defacto standards because most people in the world use WhatsApp (US excluded, and I believe a large number of people there use iMessage).

Google and others will have no choice but to add their own versions of these emojis, and hack things so that when you look up Apple's CHAI for "man reading phone on toilet" it gets diverted to Google's version of that emoji. Which seems like a mess.

Is that how it is intended to work? If so, why bother with secure hashes instead of just GUIDs?

**Comment by srl295** [comment]
> Apple and WhatsApp will adopt this new system

thanks for that, even for the sake of argument!

@Timmmm - this is a good question. This had not managed the rights management, but since the symbol was selected unambiguously, something like an "emoji store" could offer to add some symbol for you.

The hashes are designed to degrade gracefully, you can match with less precision if a smaller part of a hash is available.

**Comment by srl295** [comment]
Going to close this as answered.
